In [14]:
# Check if NumPy is installed and import it otherwise install it
try:
    import numpy as np
except ImportError:
    %pip install numpy
    import numpy as np

np.set_printoptions(suppress=True)

<Token var=<ContextVar name='format_options' default={'edgeitems': 3, 'threshold': 1000, 'floatmode': 'maxprec', 'precision': 8, 'suppress': False, 'linewidth': 75, 'nanstr': 'nan', 'infstr': 'inf', 'sign': '-', 'formatter': None, 'legacy': 9223372036854775807, 'override_repr': None} at 0x0000027207CBE0C0> at 0x0000027227E11A00>

# Завдання 1
Створіть одновимірний масив (вектор) з оберненими значеннями факторіалів
натуральних чисел, починаючи з 1, та виведіть його значення.

In [15]:
n = 10

facts = np.cumprod(np.arange(1, n+1), dtype=np.int64)
inv_facts = 1 / facts

print(f"Вектор обернених факторіалів: {inv_facts}")

Вектор обернених факторіалів: [1.         0.5        0.16666667 0.04166667 0.00833333 0.00138889
 0.00019841 0.0000248  0.00000276 0.00000028]


# Завдання 2

Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його квадратами
факторіалів кожного числа, починаючи з 1, та виведіть його значення.

In [16]:
A = np.zeros((3, 3))

for i in range(9):
    A[i // 3, i % 3] = facts[i] ** 2

print(f"Матриця A: \n{A}")

Матриця A: 
[[1.00000000e+00 4.00000000e+00 3.60000000e+01]
 [5.76000000e+02 1.44000000e+04 5.18400000e+05]
 [2.54016000e+07 1.62570240e+09 1.31681894e+11]]


# Завдання 3

Створіть масив розміром 3x3, заповніть його випадковими натуральними числами від
1 до 10 та знайдіть мін елемент.

In [17]:
B = np.zeros((3, 3))

for i in range(9):
    B[i // 3, i % 3] = np.random.randint(1, 11)

print(f"Матриця B: \n{B}")
print(f"Мінімальний елемент матриці B: {np.min(B)}")

Матриця B: 
[[3. 9. 7.]
 [7. 1. 1.]
 [3. 2. 8.]]
Мінімальний елемент матриці B: 1.0


# Завдання 4

Створіть масив розміром 2x2, заповніть його випадковими дійсними числами від -1.2
до 1.2 та виведіть його значення.

In [18]:
C = np.zeros((2, 2))

for i in range(4):
    C[i // 2, i % 2] = np.random.uniform(-1.2, 1.2)

print(f"Матриця C: \n{C}")

Матриця C: 
[[-0.86426362 -0.48762086]
 [ 0.36166573 -1.12767022]]


# Завдання 5

Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 20 до 30 та виконайте на них поелементні операції додавання, віднімання та множення.

In [19]:
arr_A = np.random.randint(20, 31, 5)
arr_B = np.random.randint(20, 31, 5)

print(f"Масив arr_A: {arr_A}")
print(f"Масив arr_B: {arr_B}")

print(f"Поелеметне множення додавання arr_A та arr_B: {arr_A + arr_B}")
print(f"Поелеметне множення віднімання arr_A та arr_B: {arr_A - arr_B}")
print(f"Поелеметне множення масивів arr_A та arr_B: {arr_A * arr_B}")


Масив arr_A: [21 30 20 21 28]
Масив arr_B: [20 27 30 24 26]
Поелеметне множення додавання arr_A та arr_B: [41 57 50 45 54]
Поелеметне множення віднімання arr_A та arr_B: [  1   3 -10  -3   2]
Поелеметне множення масивів arr_A та arr_B: [420 810 600 504 728]


# Завдання 6

Створіть дві матриці 4x4, заповніть їх довільними цілими числами від 10 до 100 та
знайдіть їх добуток.

In [20]:
D = np.random.randint(10, 101, (4, 4))

# добуток матриці
print(f"Матриця D: \n{D}")
print(f"Добуток матриці D: \n{np.dot(D, D)}")

Матриця D: 
[[14 20 35 59]
 [86 88 35 72]
 [76 66 79 23]
 [71 11 60 15]]
Добуток матриці D: 
[[ 8765  4999  7495  3956]
 [16544 12566 13175 13295]
 [14377 12795 12591 11398]
 [ 7565  6513  8510  6586]]


# Завдання 7

Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами
в діапазоні від 1 до 5 та перемножте їх між собою.

In [21]:
A = np.random.randint(1, 6, (3, 2))
B = np.random.randint(1, 6, (2, 4))

print(f"Матриця A: \n{A}")
print(f"Матриця B: \n{B}")
print(f"Добуток матриці A на B: \n{np.dot(A, B)}")

Матриця A: 
[[5 3]
 [2 2]
 [1 4]]
Матриця B: 
[[5 2 3 5]
 [5 3 4 5]]
Добуток матриці A на B: 
[[40 19 27 40]
 [20 10 14 20]
 [25 14 19 25]]


# Завдання 8

Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від 1 до 12 та знайдіть її обернену матрицю.

In [22]:
A = np.random.randint(1, 13, (3, 3))

print(f"Матриця A: \n{A}")
print(f"Обернена матриця:\n{np.invert(A)}")


Матриця A: 
[[10  1  2]
 [ 4 11 10]
 [11  7 10]]
Обернена матриця:
[[-11  -2  -3]
 [ -5 -12 -11]
 [-12  -8 -11]]


# Завдання 9

Створіть матрицю розміром 4x4, заповніть її випадковими цілими числами в діапазоні
від 0 до 1 та транспонуйте її.

In [23]:
A = np.random.randint(0, 2, (4, 4))

print(f"Матриця A: \n{A}")
print(f"Транспонована матриця:\n{np.transpose(A)}")

Матриця A: 
[[1 0 1 1]
 [1 0 0 1]
 [1 0 0 0]
 [0 0 1 1]]
Транспонована матриця:
[[1 1 1 0]
 [0 0 0 0]
 [1 0 0 1]
 [1 1 0 1]]


# Завдання 10

Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними
числами від 0 до 1, і знайдіть добуток матриці на вектор.

In [26]:
A = np.random.randint(1, 11, (3, 4))
B = np.random.randint(0, 2, 4)

print(f"Матриця A: \n{A}")
print(f"Вектор B: {B}")
print(f"Добуток матриці A на вектор B: {np.dot(A, B)}")

Матриця A: 
[[ 9  1  8  4]
 [ 7 10  8  3]
 [ 9  4  5  1]]
Вектор B: [1 0 0 1]
Добуток матриці A на вектор B: [13 10 10]


# Завдання 11

Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в
діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [27]:
A = np.random.randint(0, 2, (2, 3))
B = np.random.randint(1, 11, 3)

print(f"Матриця A: \n{A}")
print(f"Вектор B: {B}")
print(f"Добуток матриці A на вектор B: {np.dot(A, B)}")

Матриця A: 
[[1 0 1]
 [1 1 0]]
Вектор B: [ 2 10  2]
Добуток матриці A на вектор B: [ 4 12]


# Завдання 12

Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
діапазоні від 1 до 3 та знайдіть добуток всіх елементів обох матриць.

In [28]:
A = np.random.randint(1, 4, (3, 3))
B = np.random.randint(1, 4, (3, 3))

print(f"Матриця A: \n{A}")
print(f"Матриця B: \n{B}")
print(f"Добутоку всіх елементів матриць: {np.prod(A) * np.prod(B)}")

Матриця A: 
[[2 2 2]
 [1 3 2]
 [2 3 1]]
Матриця B: 
[[2 1 3]
 [3 3 2]
 [2 1 1]]
Добутоку всіх елементів матриць: 62208


# Завдання 13

Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
діапазоні від -5 до 5 та знайдіть добуток їх елементів.

In [33]:
A = np.random.randint(-5, 6, (3, 3))
B = np.random.randint(-5, 6, (3, 3))

print(f"Матриця A: \n{A}")
print(f"Матриця B: \n{B}")
print(f"Добутоку елементів матриць: \n{A * B}")

Матриця A: 
[[ 1  5 -3]
 [ 3  3 -2]
 [ 3  5  1]]
Матриця B: 
[[-5 -5 -4]
 [-2  3  5]
 [-3  3  3]]
Добутоку елементів матриць: 
[[ -5 -25  12]
 [ -6   9 -10]
 [ -9  15   3]]


# Завдання 14

Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від 1 до 10 та знайдіть середнє значення елементів на головній діагоналі.

In [34]:
A = np.random.randint(1, 11, (3, 3))

print(f"Матриця A: \n{A}")
print(f"Середнє значення діагоналі: {np.mean(np.diag(A))}")

Матриця A: 
[[ 4  8  5]
 [ 3  9  3]
 [ 1  5 10]]
Середнє значення діагоналі: 7.666666666666667


# Завдання 15

Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить найменший елемент у
кожному стовпці матриці.

In [39]:
E = np.random.uniform(-1, 1, (3, 3))
min_column = np.min(E, axis=0)
min_column = min_column.reshape((3, 1))

print(f"Матриця E: \n{E}")
print(f"Мінімальні елементи стовпців: \n{min_column}")

Матриця E: 
[[ 0.10993438 -0.44224261 -0.68728686]
 [-0.1979996   0.61404146 -0.89834227]
 [-0.99339407  0.97950902  0.77985164]]
Мінімальні елементи стовпців: 
[[-0.99339407]
 [-0.44224261]
 [-0.89834227]]
